// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1beta1 "sigs.k8s.io/ome/pkg/apis/ome/v1beta1"
	omev1beta1 "sigs.k8s.io/ome/pkg/client/clientset/versioned/typed/ome/v1beta1"
)

// fakeTrafficMaps implements TrafficMapInterface
type fakeTrafficMaps struct {
	*gentype.FakeClientWithList[*v1beta1.TrafficMap, *v1beta1.TrafficMapList]
	Fake *FakeOmeV1beta1
}

func newFakeTrafficMaps(fake *FakeOmeV1beta1, namespace string) omev1beta1.TrafficMapInterface {
	return &fakeTrafficMaps{
		gentype.NewFakeClientWithList[*v1beta1.TrafficMap, *v1beta1.TrafficMapList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("trafficmaps"),
			v1beta1.SchemeGroupVersion.WithKind("TrafficMap"),
			func() *v1beta1.TrafficMap { return &v1beta1.TrafficMap{} },
			func() *v1beta1.TrafficMapList { return &v1beta1.TrafficMapList{} },
			func(dst, src *v1beta1.TrafficMapList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.TrafficMapList) []*v1beta1.TrafficMap { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.TrafficMapList, items []*v1beta1.TrafficMap) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
