// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	apisomev1beta1 "sigs.k8s.io/ome/pkg/apis/ome/v1beta1"
	versioned "sigs.k8s.io/ome/pkg/client/clientset/versioned"
	internalinterfaces "sigs.k8s.io/ome/pkg/client/informers/externalversions/internalinterfaces"
	omev1beta1 "sigs.k8s.io/ome/pkg/client/listers/ome/v1beta1"
)

// TrafficMapInformer provides access to a shared informer and lister for
// TrafficMaps.
type TrafficMapInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() omev1beta1.TrafficMapLister
}

type trafficMapInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTrafficMapInformer constructs a new informer for TrafficMap type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTrafficMapInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTrafficMapInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTrafficMapInformer constructs a new informer for TrafficMap type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTrafficMapInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().TrafficMaps(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().TrafficMaps(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().TrafficMaps(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().TrafficMaps(namespace).Watch(ctx, options)
			},
		},
		&apisomev1beta1.TrafficMap{},
		resyncPeriod,
		indexers,
	)
}

func (f *trafficMapInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTrafficMapInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *trafficMapInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisomev1beta1.TrafficMap{}, f.defaultInformer)
}

func (f *trafficMapInformer) Lister() omev1beta1.TrafficMapLister {
	return omev1beta1.NewTrafficMapLister(f.Informer().GetIndexer())
}
