package v1beta1

import (
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"knative.dev/pkg/apis"
)

// TrafficMapProgrammed is the condition type reporting whether the active
// publisher has realized this TrafficMap onto a concrete data plane (e.g. a
// Gateway API HTTPRoute). Its status mirrors spec.programmed.
const TrafficMapProgrammed = "Programmed"

// TrafficMapRoutable is the condition type reporting whether this map carries a
// target a gateway can send traffic to. It is owned by the routing controller,
// which writes it on every pass so an empty table always explains itself: the
// map exists for the whole life of a routed InferenceService, and emptiness is a
// state of the map rather than its absence.
const TrafficMapRoutable = "Routable"

// Reasons for the Routable condition. NotPlaced and NoAddressableHome accompany
// Routable=False and an empty table; AllHomesUnready accompanies Routable=True,
// because the weight fallback still spreads traffic across homes that are
// addressable but not yet ready rather than black-holing it.
const (
	TrafficMapReasonRoutable          = "Routable"
	TrafficMapReasonNotPlaced         = "NotPlaced"
	TrafficMapReasonNoAddressableHome = "NoAddressableHome"
	TrafficMapReasonAllHomesUnready   = "AllHomesUnready"
)

// CapacitySource names which input produced an entry's Allocated count.
// +kubebuilder:validation:Enum=ControlPlane;Endpoint
type CapacitySource string

const (
	// CapacitySourceControlPlane means Allocated came from the control plane's
	// own view — status.placement intersected with quota. The default.
	CapacitySourceControlPlane CapacitySource = "ControlPlane"

	// CapacitySourceEndpoint means the home reported a lower servable capacity
	// than the plan and that report became Allocated. A reported value is only
	// ever a ceiling, so this source implies Allocated is below the plan.
	CapacitySourceEndpoint CapacitySource = "Endpoint"
)

// ProbeResult is the outcome of the most recent end-to-end health probe.
// +kubebuilder:validation:Enum=Passing;Failing;Unknown
type ProbeResult string

const (
	// ProbeResultPassing means the last probe reached the endpoint and got an
	// accepted status.
	ProbeResultPassing ProbeResult = "Passing"

	// ProbeResultFailing means the last probe reached a verdict that counts
	// against the home: a gating status code, a transport error, or a timeout.
	// It gates the weight only once the consecutive-failure threshold is met.
	ProbeResultFailing ProbeResult = "Failing"

	// ProbeResultUnknown means no verdict was reached — the probe has not run
	// yet, or it could not run at all (missing credentials, blocked egress, a
	// misconfigured prober). Unknown never gates: that condition is uniform
	// across homes, so treating it as failure would zero the whole fleet at once.
	ProbeResultUnknown ProbeResult = "Unknown"
)

// TrafficMap is the capacity-aware routing projection of one multi-cluster
// InferenceService: the per-home traffic split a gateway consumes. Placement
// decides WHERE an ISVC's replicas run and quota decides HOW MUCH each home may
// run; TrafficMap decides the WEIGHTS. It is generated by a control-plane
// routing controller from status.placement plus accelerator-quota allocation,
// never hand-edited, and consumed by a gateway-neutral publisher.
//
// One TrafficMap exists per routed ISVC, named after it and owned by it (so it
// is garbage-collected with the ISVC), for as long as that ISVC is routed --
// including while no home is routable, when the table is empty and the
// Routable condition says why. The routing controller owns spec and the
// Routable condition; the publisher owns the rest of status.
// +genclient
// +k8s:openapi-gen=true
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=tm;tmap
// +kubebuilder:printcolumn:name="Mode",type=string,JSONPath=`.spec.mode`
// +kubebuilder:printcolumn:name="Programmed",type=string,JSONPath=`.status.conditions[?(@.type=="Programmed")].status`
// +kubebuilder:printcolumn:name="Routable",type=string,JSONPath=`.status.conditions[?(@.type=="Routable")].status`
// +kubebuilder:printcolumn:name="Reason",type=string,JSONPath=`.status.conditions[?(@.type=="Routable")].reason`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
type TrafficMap struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   TrafficMapSpec   `json:"spec,omitempty"`
	Status TrafficMapStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TrafficMapList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TrafficMap `json:"items"`
}

// TrafficMapSpec is the computed routing table. It is a machine-written
// declarative artifact — the routing controller recomputes it whenever
// status.placement or the home's quota allocation changes; the publisher
// consumes it as desired state. A validating webhook may reject writes from
// non-controller users.
type TrafficMapSpec struct {
	// Service is the routed logical service — the InferenceService name. Equal to
	// metadata.name in v1; a distinct field leaves room for a future
	// many-ISVC-to-one-service map.
	// +required
	Service string `json:"service"`

	// Mode mirrors the ISVC's spec.placement.mode (Single/All/Split) so a
	// consumer can read the routing intent without reading the ISVC.
	// +optional
	Mode PlacementMode `json:"mode,omitempty"`

	// Entries is the routing table: one entry per serving home, each with its
	// endpoint, final apply-verbatim weight, and the capacity/health provenance
	// of that weight. Consumers apply the weights directly — no gating, fallback,
	// or normalization is left for them to redo.
	// +optional
	// +listType=map
	// +listMapKey=cluster
	Entries []TrafficMapEntry `json:"entries,omitempty"`

	// ObservedISVCGeneration is the InferenceService generation this table was
	// computed from, so a consumer can detect staleness relative to the source.
	// +optional
	ObservedISVCGeneration int64 `json:"observedISVCGeneration,omitempty"`
}

// TrafficMapEntry is one serving home's routing target and the provenance of its
// weight.
type TrafficMapEntry struct {
	// Cluster is the WorkloadCluster serving this home.
	// +required
	Cluster string `json:"cluster"`

	// Endpoint is the home's externally-addressable URL, taken from
	// status.placement.candidates[].endpoint.
	// +optional
	Endpoint *apis.URL `json:"endpoint,omitempty"`

	// Weight is the home's final, normalized, capacity-planned, health-gated
	// traffic share as a relative non-negative integer (matching Gateway API and
	// Envoy weighted-cluster semantics). A consumer either applies it verbatim or
	// divides by the sum of weights for a percentage. When every home is unhealthy
	// the controller writes equal weights rather than all-zero, so traffic is
	// never black-holed.
	// +optional
	// +kubebuilder:validation:Minimum=0
	Weight int32 `json:"weight"`

	// Healthy is the health-gate result for this home (readyReplicas > 0). An
	// unhealthy home is weighted 0 (unless every home is unhealthy).
	// +optional
	Healthy bool `json:"healthy"`

	// Capacity is the provenance of Weight: weight is proportional to
	// allocated * factor, gated to 0 when the home has no ready replicas.
	// +optional
	Capacity *TrafficMapCapacity `json:"capacity,omitempty"`

	// Probe is the active end-to-end health probe's contribution to Healthy,
	// present only when probing is configured. Healthy alone does not say
	// whether readiness or reachability failed, and those are different faults
	// with different owners: readiness is the workload's, reachability is the
	// path's (ingress, DNS, certificate, route).
	// +optional
	Probe *TrafficMapProbe `json:"probe,omitempty"`
}

// TrafficMapProbe records what the active end-to-end probe observed for one
// home. The probe targets the entry's Endpoint — the URL a client uses — so it
// covers the whole serving path rather than pod readiness inside the home.
type TrafficMapProbe struct {
	// Result is the most recent probe verdict. Only a sustained Failing gates
	// the weight; Unknown never does.
	// +optional
	Result ProbeResult `json:"result,omitempty"`

	// LastProbeTime is when the probe last reached a verdict, so a stalled
	// prober is visible rather than being read as a steady pass.
	// +optional
	LastProbeTime *metav1.Time `json:"lastProbeTime,omitempty"`

	// ConsecutiveFailures counts unbroken Failing verdicts. The weight is gated
	// only once this reaches the configured failure threshold: a single dropped
	// packet must not move a large traffic share, and the reprogramming churn
	// from flapping would itself be the outage.
	// +optional
	// +kubebuilder:validation:Minimum=0
	ConsecutiveFailures int32 `json:"consecutiveFailures,omitempty"`

	// Message explains the current Result — the observed status code, the
	// transport error, or why the probe could not run.
	// +optional
	Message string `json:"message,omitempty"`
}

// TrafficMapCapacity records why an entry's weight is what it is.
type TrafficMapCapacity struct {
	// Allocated is the number of replicas this home is intended to run for the
	// ISVC — the Split apportionment intersected with what the home's
	// AcceleratorQuota admitted. It is the count basis of the weight.
	// +optional
	Allocated int32 `json:"allocated,omitempty"`

	// Ready is the home's live ready-replica count — the health signal. Zero
	// means the entry is health-gated to weight 0.
	// +optional
	Ready int32 `json:"ready,omitempty"`

	// Factor is the per-replica relative serving capacity of this home's
	// accelerator (baseline "1", higher = faster), so heterogeneous hardware is
	// weighted by capacity rather than raw replica count: weight is proportional
	// to allocated * factor. Defaults to "1" (homogeneous) when unset — the
	// multiplicative identity, i.e. no scaling. It is operator-supplied config,
	// never derived from raw hardware FLOPS.
	// +optional
	// +kubebuilder:default="1"
	Factor *resource.Quantity `json:"factor,omitempty"`

	// Source names which input produced Allocated. Without it an operator
	// reading an unexpected weight cannot tell "the home reported less capacity"
	// from "the endpoint source was configured but failed open and the plan was
	// used" — the same number with opposite remediations.
	// +optional
	// +kubebuilder:default=ControlPlane
	Source CapacitySource `json:"source,omitempty"`

	// Reported is the home's own servable-capacity figure, recorded whenever the
	// endpoint source answered — including when it was at or above the plan and
	// therefore did not lower Allocated. Keeping it visible in that case is what
	// makes the ceiling auditable: Allocated alone cannot show that a report was
	// received and found non-binding.
	// +optional
	// +kubebuilder:validation:Minimum=0
	Reported *int32 `json:"reported,omitempty"`
}

// TrafficMapStatus reports whether the active publisher has realized this map
// onto a concrete data plane, and whether the map has anything to realize.
// Two writers share it: the publisher owns Programmed, GatewayRef and
// ObservedTrafficMapGeneration, and the routing controller owns the Routable
// condition. Conditions is keyed on type, so each writer must patch only its
// own and never rewrite the list.
type TrafficMapStatus struct {
	// Programmed reports whether the active publisher has realized this map onto
	// its data plane.
	// +optional
	Programmed bool `json:"programmed,omitempty"`

	// GatewayRef identifies the data plane object realizing this map (e.g. the
	// HTTPRoute the Gateway API publisher created). Empty until programmed.
	// +optional
	GatewayRef *TrafficMapGatewayRef `json:"gatewayRef,omitempty"`

	// ObservedTrafficMapGeneration is the spec generation the publisher last
	// realized, so lag between generation and realization is observable.
	// +optional
	ObservedTrafficMapGeneration int64 `json:"observedTrafficMapGeneration,omitempty"`

	// Conditions carry the Programmed condition.
	// +optional
	// +listType=map
	// +listMapKey=type
	// +patchStrategy=merge
	// +patchMergeKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type"`
}

// TrafficMapGatewayRef points at the data plane object a publisher created to
// realize a TrafficMap.
type TrafficMapGatewayRef struct {
	// Group is the API group of the realizing object (e.g.
	// "gateway.networking.k8s.io"). Empty means the core group.
	// +optional
	Group string `json:"group,omitempty"`

	// Kind is the object kind (e.g. "HTTPRoute").
	// +required
	Kind string `json:"kind"`

	// Name is the object name.
	// +required
	Name string `json:"name"`

	// Namespace is the object namespace. Empty means the TrafficMap's namespace.
	// +optional
	Namespace string `json:"namespace,omitempty"`
}

func init() {
	SchemeBuilder.Register(&TrafficMap{}, &TrafficMapList{})
}
