// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	omev1beta1 "sigs.k8s.io/ome/pkg/apis/ome/v1beta1"
)

// TrafficMapLister helps list TrafficMaps.
// All objects returned here must be treated as read-only.
type TrafficMapLister interface {
	// List lists all TrafficMaps in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*omev1beta1.TrafficMap, err error)
	// TrafficMaps returns an object that can list and get TrafficMaps.
	TrafficMaps(namespace string) TrafficMapNamespaceLister
	TrafficMapListerExpansion
}

// trafficMapLister implements the TrafficMapLister interface.
type trafficMapLister struct {
	listers.ResourceIndexer[*omev1beta1.TrafficMap]
}

// NewTrafficMapLister returns a new TrafficMapLister.
func NewTrafficMapLister(indexer cache.Indexer) TrafficMapLister {
	return &trafficMapLister{listers.New[*omev1beta1.TrafficMap](indexer, omev1beta1.Resource("trafficmap"))}
}

// TrafficMaps returns an object that can list and get TrafficMaps.
func (s *trafficMapLister) TrafficMaps(namespace string) TrafficMapNamespaceLister {
	return trafficMapNamespaceLister{listers.NewNamespaced[*omev1beta1.TrafficMap](s.ResourceIndexer, namespace)}
}

// TrafficMapNamespaceLister helps list and get TrafficMaps.
// All objects returned here must be treated as read-only.
type TrafficMapNamespaceLister interface {
	// List lists all TrafficMaps in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*omev1beta1.TrafficMap, err error)
	// Get retrieves the TrafficMap from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*omev1beta1.TrafficMap, error)
	TrafficMapNamespaceListerExpansion
}

// trafficMapNamespaceLister implements the TrafficMapNamespaceLister
// interface.
type trafficMapNamespaceLister struct {
	listers.ResourceIndexer[*omev1beta1.TrafficMap]
}
