// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	omev1beta1 "sigs.k8s.io/ome/pkg/apis/ome/v1beta1"
	scheme "sigs.k8s.io/ome/pkg/client/clientset/versioned/scheme"
)

// TrafficMapsGetter has a method to return a TrafficMapInterface.
// A group's client should implement this interface.
type TrafficMapsGetter interface {
	TrafficMaps(namespace string) TrafficMapInterface
}

// TrafficMapInterface has methods to work with TrafficMap resources.
type TrafficMapInterface interface {
	Create(ctx context.Context, trafficMap *omev1beta1.TrafficMap, opts v1.CreateOptions) (*omev1beta1.TrafficMap, error)
	Update(ctx context.Context, trafficMap *omev1beta1.TrafficMap, opts v1.UpdateOptions) (*omev1beta1.TrafficMap, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, trafficMap *omev1beta1.TrafficMap, opts v1.UpdateOptions) (*omev1beta1.TrafficMap, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*omev1beta1.TrafficMap, error)
	List(ctx context.Context, opts v1.ListOptions) (*omev1beta1.TrafficMapList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *omev1beta1.TrafficMap, err error)
	TrafficMapExpansion
}

// trafficMaps implements TrafficMapInterface
type trafficMaps struct {
	*gentype.ClientWithList[*omev1beta1.TrafficMap, *omev1beta1.TrafficMapList]
}

// newTrafficMaps returns a TrafficMaps
func newTrafficMaps(c *OmeV1beta1Client, namespace string) *trafficMaps {
	return &trafficMaps{
		gentype.NewClientWithList[*omev1beta1.TrafficMap, *omev1beta1.TrafficMapList](
			"trafficmaps",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *omev1beta1.TrafficMap { return &omev1beta1.TrafficMap{} },
			func() *omev1beta1.TrafficMapList { return &omev1beta1.TrafficMapList{} },
		),
	}
}
